version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - ./webapp/:/opt/shibboleth-idp/dist/webapp/
      - ./messages/:/opt/shibboleth-idp/messages/
      - ./config/shib-idp/conf:/opt/shibboleth-idp/conf/examples


volumes:
  webapp:
  messages:
  conf:
